version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:12
    container_name: laravel_db
    environment:
      POSTGRES_DB: tester
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: arquin
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
